#!/bin/bash
   
# Date : (2011-11-06 18-56)
# Last revision : (2014-12-25 11-59)
# Wine version used : System
# Distribution used to test :
# Author : thib25 & Tutul (update) && andykimpe (update)
   
# CHANGELOG
# [SuperPlumus] (2014-12-25 11-59)
#   Update Wine version 1.3.5 -> System
#   Update 7-Zip version 4.65 -> 9.20
#   Update messages
#   Change title and prefix names
# [SuperPlumus] (2014-12-25 11-59)
#   Clean code
   
 
[ "$PLAYONLINUX" = "" ] && exit
source "$PLAYONLINUX/lib/sources"
   
TITLE="7-Zip"
PREFIX="7zip"
   
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/7zip/top.jpg" "http://files.playonlinux.com/resources/setups/7zip/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_SetupWindow_SetID 373
POL_Debug_Init
   
POL_SetupWindow_presentation "$TITLE" "7-Zip" "http://www.7-zip.org" "andykimpe" "$PREFIX"
   
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate
   
POL_System_TmpCreate "$PREFIX"
   
POL_Call POL_Install_LunaTheme
   
cd "$POL_System_TmpDir"
if [ "$POL_ARCH" == "amd64" ]; then
    POL_Download "https://www.7-zip.org/a/7z1805-x64.exe" "1deefe6649699946590856e901bbe5ff"
    POL_Wine_WaitBefore "$TITLE"
    POL_AutoWine "7z1805-x64.msi"
else
    POL_Download "https://www.7-zip.org/a/7z1805.exe" "80ccb79bceed759d69cc2f80be5eaaed"
    POL_Wine_WaitBefore "$TITLE"
    POL_Wine 7z1805.exe
fi
 
POL_System_TmpDelete
   
POL_Shortcut "7zFM.exe" "$TITLE"
   
POL_SetupWindow_Close
exit